function GUI_Tiristores
    fig_tir = figure('Name','Modulo Tiristores',...
        'NumberTitle','off',...
        'Position',[550 350 350 250], 'MenuBar', 'none');

    uicontrol('Style','text','Position',[20 200 310 20],...
        'String','Simulación de disparo de fase', 'FontWeight', 'bold');

    uicontrol('Style','text','Position',[20 150 120 20],'String','Ángulo disparo (°):');
    
    edit_ang = uicontrol('Style','edit','Position',[150 150 60 25],'String','90');
    
    uicontrol('Style','slider','Min',0,'Max',180,'Value',90,...
        'Position',[20 110 310 20],...
        'Callback', @(s,e) set(edit_ang, 'String', num2str(round(get(s,'Value')))));

    uicontrol('Style','pushbutton','Position',[125 40 100 35],...
        'String','Simular Disparo',...
        'Callback', @(s,e) msgbox(['Ángulo: ' get(edit_ang,'String') '°']));
end
