function GUI_DC

    fig_dc = figure('Name','Modulo DC',...
        'NumberTitle','off',...
        'Position',[550 350 350 250], 'MenuBar', 'none');
    
    uicontrol('Style','text','Position',[20 200 310 20],...
        'String','Simulación de voltaje DC', 'FontWeight', 'bold');

    uicontrol('Style','text','Position',[20 150 100 20],'String','Voltaje (V):');
    
    edit_v = uicontrol('Style','edit','Position',[130 150 60 25],'String','12');
    
    slider_v = uicontrol('Style','slider','Min',0,'Max',24,'Value',12,...
        'Position',[20 110 310 20],...
        'Callback', @(s,e) set(edit_v, 'String', num2str(round(get(s,'Value'),1))));

    uicontrol('Style','pushbutton','Position',[125 40 100 35],...
        'String','Simular DC',...
        'Callback', @(s,e) msgbox(['Voltaje DC: ' get(edit_v,'String') ' V']));
end

