function GUI_Control

fig_ctrl = figure('Name','Módulo de Control 9060',...
        'NumberTitle','off',...
        'Position',[550 350 350 200], 'MenuBar', 'none');

    uicontrol('Style','text',...
        'Position',[10 150 330 30],...
        'String','Configuración de Control LabVolt',...
        'FontSize', 11, 'FontWeight', 'bold');

    % Etiqueta y Valor Fijo
    uicontrol('Style','text','Position',[50 100 120 20],...
        'String','Modelo por defecto:', 'HorizontalAlignment', 'right');

    % Usamos un estilo 'edit' pero con Enable 'off' para que se vea pero no se toque
    uicontrol('Style','edit',...
        'Position',[180 100 80 25],...
        'String','9060',...
        'Enable', 'off',... 
        'FontSize', 10, 'FontWeight', 'bold', 'ForegroundColor', [0 0 0]);

    % Botón único de acción
    uicontrol('Style','pushbutton',...
        'Position',[100 40 150 40],...
        'String','Iniciar Control',...
        'BackgroundColor', [0.7 1 0.7],...
        'Callback', @(s,e) msgbox('Iniciando sistema de control LabVolt 9060...', 'Status'));
end
